### ISSUE TITLE
includedir directive breaks sudoers on older versions if directory does not exist

### ISSUE THREAD

**Issue by TJuberg** [saltstack-formulas/sudoers-formula#25]
I'm not sure one would want to bother as this should affect very few distributions.

On RHEL5/CentOS5, the /etc/sudoers.d directory does not exist by default, and /etc/sudoers.d is by default set as an includedir by the formula. 

The bug in older versions of sudo means that the sudoers file will be seen as corrupt, leaving sudo broken when this directory does not exist.

A solution would be to have the formula create the directory, bypassing this issue. Then again, given the limited scope of this issue, it might not be worth doing anything about it.

I'm not sure if the issue remains present on sudo bundled with newer distributions, as they usually have a sudoers.d directory by default, thus making this a non issue for them in any case.

**Comment by 0xf10e** [comment]
The templating needed to work around this issue should be rather simple. As long as it just affects RHEL & derivates < 6 you can check for `grains[os_family] == "RedHat"` and `grains[os_version[0]] < 6` (I guess, haven't checked the grain's name).
The same if-statememt can be used around the state for the directory and in the template for sudoers.

Could be tagged as "low hanging fruit" ;)

**Comment by llua** [comment]
sudo in openbsd's ports/packages also does not create /etcc/sudoers.d. i was adding support for the os when i ran into the issue.

**Comment by tjuup** [comment]
you can easily fix this by adding "makedirs: True" to file.managed in included.sls

Thx for making this formula :-)

**Comment by javierbertoli** [comment]
Should be fixed now.
