### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by stonefury** [saltstack-formulas/sudoers-formula#38]
Could someone give actual example of how to add a user to the sudoers file?  What are the arguments for example? Or is that supposed to be obvious from the pillar? Thanks :)

**Comment by 0xf10e** [comment]
I guess it's obvious for those who know how the sudoers file works. But you can just use the first four lines from `pillar.example` to allow the user `johndoe` to run any command on any host (which uses this file) as any user.

**Comment by stonefury** [comment]
Yep, got it working. Thank you.  New to salt stack, I think I was looking for a state file example, but when I used a pillar as the configuration then it worked out fine.
